/*

 MAP1.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 32
   Tile set      : C:\Users\diego\Desktop\gbdk\perautarpg\tileset1.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define map1Width 32
#define map1Height 32
#define map1Bank 0

extern unsigned char map1[];

/* End of MAP1.H */
