/*

 TILESET1.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : Tile-count as Constant.
  Tile size            : 8 x 8
  Tiles                : 0 to 32

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define tileset1Bank 0

/* Super Gameboy palette 0 */
#define tileset1SGBPal0c0 6076
#define tileset1SGBPal0c1 8935
#define tileset1SGBPal0c2 6596
#define tileset1SGBPal0c3 5344

/* Super Gameboy palette 1 */
#define tileset1SGBPal1c0 6076
#define tileset1SGBPal1c1 8935
#define tileset1SGBPal1c2 6596
#define tileset1SGBPal1c3 5344

/* Super Gameboy palette 2 */
#define tileset1SGBPal2c0 6076
#define tileset1SGBPal2c1 8935
#define tileset1SGBPal2c2 6596
#define tileset1SGBPal2c3 5344

/* Super Gameboy palette 3 */
#define tileset1SGBPal3c0 6076
#define tileset1SGBPal3c1 8935
#define tileset1SGBPal3c2 6596
#define tileset1SGBPal3c3 5344

/* Gameboy Color palette 0 */
#define tileset1CGBPal0c0 992
#define tileset1CGBPal0c1 31
#define tileset1CGBPal0c2 31744
#define tileset1CGBPal0c3 0

/* Gameboy Color palette 1 */
#define tileset1CGBPal1c0 32767
#define tileset1CGBPal1c1 21140
#define tileset1CGBPal1c2 10570
#define tileset1CGBPal1c3 0

/* Gameboy Color palette 2 */
#define tileset1CGBPal2c0 0
#define tileset1CGBPal2c1 10570
#define tileset1CGBPal2c2 21140
#define tileset1CGBPal2c3 32767

/* Gameboy Color palette 3 */
#define tileset1CGBPal3c0 0
#define tileset1CGBPal3c1 31
#define tileset1CGBPal3c2 311
#define tileset1CGBPal3c3 25368

/* Gameboy Color palette 4 */
#define tileset1CGBPal4c0 6076
#define tileset1CGBPal4c1 8935
#define tileset1CGBPal4c2 6596
#define tileset1CGBPal4c3 5344

/* Gameboy Color palette 5 */
#define tileset1CGBPal5c0 26626
#define tileset1CGBPal5c1 895
#define tileset1CGBPal5c2 8231
#define tileset1CGBPal5c3 32767

/* Gameboy Color palette 6 */
#define tileset1CGBPal6c0 1322
#define tileset1CGBPal6c1 26630
#define tileset1CGBPal6c2 31725
#define tileset1CGBPal6c3 471

/* Gameboy Color palette 7 */
#define tileset1CGBPal7c0 992
#define tileset1CGBPal7c1 31
#define tileset1CGBPal7c2 32767
#define tileset1CGBPal7c3 0
/* CGBpalette entries. */
extern unsigned char tileset1CGB[];
/* Start of tile array. */
extern unsigned char tileset1[];
#define tileset1Len 33

/* End of TILESET1.H */
