/*

 TILESET1.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : Tile-count as Constant.
  Tile size            : 8 x 8
  Tiles                : 0 to 32

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : 4 Bits per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define tileset1Bank 0
/* CGBpalette entries. */
extern unsigned char tileset1CGB[];
/* Start of tile array. */
extern unsigned char tileset1[];
#define tileset1Len 33

/* End of TILESET1.H */
