/*

 HOUSE_01.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 16
   Tile set      : C:\Users\diego\Desktop\gbdk\perautarpg\assets\tilesets\interior_01.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define house_01Width 20
#define house_01Height 16
#define house_01Bank 0

extern unsigned char house_01_tiledata[];
extern unsigned char house_01_attributes[];

/* End of HOUSE_01.H */
