/*

 TOWN_01.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 16
   Tile set      : C:\Users\diego\Desktop\gbdk\perautarpg\assets\tilesets\exterior_01.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define town_01Width 20
#define town_01Height 16
#define town_01Bank 0

extern unsigned char town_01[];

/* End of TOWN_01.H */
