/*

 BORDER.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : Tile-count as Constant.
  Tile size            : 8 x 8
  Tiles                : 0 to 38

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define borderBank 0

/* Super Gameboy palette 0 */
#define borderSGBPal0c0 6076
#define borderSGBPal0c1 8935
#define borderSGBPal0c2 6596
#define borderSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define borderSGBPal1c0 6076
#define borderSGBPal1c1 8935
#define borderSGBPal1c2 6596
#define borderSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define borderSGBPal2c0 6076
#define borderSGBPal2c1 8935
#define borderSGBPal2c2 6596
#define borderSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define borderSGBPal3c0 6076
#define borderSGBPal3c1 8935
#define borderSGBPal3c2 6596
#define borderSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define borderCGBPal0c0 6076
#define borderCGBPal0c1 8935
#define borderCGBPal0c2 6596
#define borderCGBPal0c3 5344

/* Gameboy Color palette 1 */
#define borderCGBPal1c0 6076
#define borderCGBPal1c1 8935
#define borderCGBPal1c2 6596
#define borderCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define borderCGBPal2c0 6076
#define borderCGBPal2c1 8935
#define borderCGBPal2c2 6596
#define borderCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define borderCGBPal3c0 6076
#define borderCGBPal3c1 8935
#define borderCGBPal3c2 6596
#define borderCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define borderCGBPal4c0 6076
#define borderCGBPal4c1 8935
#define borderCGBPal4c2 6596
#define borderCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define borderCGBPal5c0 6076
#define borderCGBPal5c1 8935
#define borderCGBPal5c2 6596
#define borderCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define borderCGBPal6c0 6076
#define borderCGBPal6c1 8935
#define borderCGBPal6c2 6596
#define borderCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define borderCGBPal7c0 32767
#define borderCGBPal7c1 25368
#define borderCGBPal7c2 16912
#define borderCGBPal7c3 0
/* CGBpalette entries. */
extern unsigned char borderCGB[];
/* Start of tile array. */
extern unsigned char border[];
#define borderLen 39

/* End of BORDER.H */
