/*

 INTERIOR_01.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : Tile-count as Constant.
  Tile size            : 8 x 8
  Tiles                : 0 to 53

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define interior_01Bank 0

/* Super Gameboy palette 0 */
#define interior_01SGBPal0c0 6076
#define interior_01SGBPal0c1 8935
#define interior_01SGBPal0c2 6596
#define interior_01SGBPal0c3 5344

/* Super Gameboy palette 1 */
#define interior_01SGBPal1c0 6076
#define interior_01SGBPal1c1 8935
#define interior_01SGBPal1c2 6596
#define interior_01SGBPal1c3 5344

/* Super Gameboy palette 2 */
#define interior_01SGBPal2c0 6076
#define interior_01SGBPal2c1 8935
#define interior_01SGBPal2c2 6596
#define interior_01SGBPal2c3 5344

/* Super Gameboy palette 3 */
#define interior_01SGBPal3c0 6076
#define interior_01SGBPal3c1 8935
#define interior_01SGBPal3c2 6596
#define interior_01SGBPal3c3 5344

/* Gameboy Color palette 0 */
#define interior_01CGBPal0c0 27550
#define interior_01CGBPal0c1 20083
#define interior_01CGBPal0c2 13741
#define interior_01CGBPal0c3 7399

/* Gameboy Color palette 1 */
#define interior_01CGBPal1c0 27550
#define interior_01CGBPal1c1 25215
#define interior_01CGBPal1c2 6494
#define interior_01CGBPal1c3 7399

/* Gameboy Color palette 2 */
#define interior_01CGBPal2c0 10002
#define interior_01CGBPal2c1 1679
#define interior_01CGBPal2c2 425
#define interior_01CGBPal2c3 7399

/* Gameboy Color palette 3 */
#define interior_01CGBPal3c0 27550
#define interior_01CGBPal3c1 32271
#define interior_01CGBPal3c2 32041
#define interior_01CGBPal3c3 7399

/* Gameboy Color palette 4 */
#define interior_01CGBPal4c0 18202
#define interior_01CGBPal4c1 7733
#define interior_01CGBPal4c2 3504
#define interior_01CGBPal4c3 7399

/* Gameboy Color palette 5 */
#define interior_01CGBPal5c0 6076
#define interior_01CGBPal5c1 8935
#define interior_01CGBPal5c2 6596
#define interior_01CGBPal5c3 5344

/* Gameboy Color palette 6 */
#define interior_01CGBPal6c0 6076
#define interior_01CGBPal6c1 8935
#define interior_01CGBPal6c2 6596
#define interior_01CGBPal6c3 5344

/* Gameboy Color palette 7 */
#define interior_01CGBPal7c0 6076
#define interior_01CGBPal7c1 8935
#define interior_01CGBPal7c2 6596
#define interior_01CGBPal7c3 5344
/* CGBpalette entries. */
extern unsigned char interior_01CGB[];
/* Start of tile array. */
extern unsigned char interior_01[];
#define interior_01Len 54

/* End of INTERIOR_01.H */
