/*

 SPRITES_01.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : Tile-count as Constant.
  Tile size            : 8 x 16
  Tiles                : 0 to 2

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define sprites_01Bank 0

/* Super Gameboy palette 0 */
#define sprites_01SGBPal0c0 6076
#define sprites_01SGBPal0c1 8935
#define sprites_01SGBPal0c2 6596
#define sprites_01SGBPal0c3 5344

/* Super Gameboy palette 1 */
#define sprites_01SGBPal1c0 6076
#define sprites_01SGBPal1c1 8935
#define sprites_01SGBPal1c2 6596
#define sprites_01SGBPal1c3 5344

/* Super Gameboy palette 2 */
#define sprites_01SGBPal2c0 6076
#define sprites_01SGBPal2c1 8935
#define sprites_01SGBPal2c2 6596
#define sprites_01SGBPal2c3 5344

/* Super Gameboy palette 3 */
#define sprites_01SGBPal3c0 6076
#define sprites_01SGBPal3c1 8935
#define sprites_01SGBPal3c2 6596
#define sprites_01SGBPal3c3 5344

/* Gameboy Color palette 0 */
#define sprites_01CGBPal0c0 6076
#define sprites_01CGBPal0c1 8935
#define sprites_01CGBPal0c2 6596
#define sprites_01CGBPal0c3 5344

/* Gameboy Color palette 1 */
#define sprites_01CGBPal1c0 32767
#define sprites_01CGBPal1c1 16912
#define sprites_01CGBPal1c2 31
#define sprites_01CGBPal1c3 0

/* Gameboy Color palette 2 */
#define sprites_01CGBPal2c0 6076
#define sprites_01CGBPal2c1 8935
#define sprites_01CGBPal2c2 6596
#define sprites_01CGBPal2c3 5344

/* Gameboy Color palette 3 */
#define sprites_01CGBPal3c0 6076
#define sprites_01CGBPal3c1 8935
#define sprites_01CGBPal3c2 6596
#define sprites_01CGBPal3c3 5344

/* Gameboy Color palette 4 */
#define sprites_01CGBPal4c0 6076
#define sprites_01CGBPal4c1 8935
#define sprites_01CGBPal4c2 6596
#define sprites_01CGBPal4c3 5344

/* Gameboy Color palette 5 */
#define sprites_01CGBPal5c0 6076
#define sprites_01CGBPal5c1 8935
#define sprites_01CGBPal5c2 6596
#define sprites_01CGBPal5c3 5344

/* Gameboy Color palette 6 */
#define sprites_01CGBPal6c0 6076
#define sprites_01CGBPal6c1 8935
#define sprites_01CGBPal6c2 6596
#define sprites_01CGBPal6c3 5344

/* Gameboy Color palette 7 */
#define sprites_01CGBPal7c0 6076
#define sprites_01CGBPal7c1 8935
#define sprites_01CGBPal7c2 6596
#define sprites_01CGBPal7c3 5344
/* CGBpalette entries. */
extern unsigned char sprites_01CGB[];
/* Start of tile array. */
extern unsigned char sprites_01[];
#define sprites_01Len 3

/* End of SPRITES_01.H */
